In [1]:
import numpy as np

In [5]:
a = np.arange(15).reshape(3,5)

In [6]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
b = np.array([6,7,8])

In [8]:
b

array([6, 7, 8])

In [11]:
from numpy import pi

In [12]:
x = np.linspace( 0, 2*pi, 100 )  

In [13]:
f = np.sin(x)

In [16]:
b = np.arange(12).reshape(4,3)  

In [17]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
c = np.arange(24).reshape(2,3,4)  

In [19]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])